project:
  type: website
  output-dir: docs

website:
  title: "Patrick Heldebrandt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: EPPS6323 Assignments
        menu:
          - href: Assignment1.qmd
            text: Assignment1
          - href: Assignment2.qmd
            text: Assignment2
          - href: Assignment3.qmd
            text: Assignment3
          - href: Assignment4.qmd
          - text: Assignment4
      - href: projects.qmd
        text: Projects
      - text: Participation 
        menu: 
          - href: weeklyreflections.qmd
            text: Weekly Reflections
          - href: log.qmd
            text: AI Collaboration Log
          - href: readingnotebook.qmd
            text: Reading Notebook            
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

